### ISSUE TITLE
svgcleaner does not handle files without the svg extension

### ISSUE THREAD

**Issue by desbma** [RazrFalcon/svgcleaner#207]
svgcleaner refuses to handle valid SVG files if they do not have the `svg` extension:
`Error: Invalid value for '<in-file>': The file format must be SVG.`

This is a minor issue, but it is unusual for command line tools to rely on file extensions to identify formats, so I think it should be fixed.

Thanks

**Comment by JoKalliauer** [comment]
@desbma Seems to be a duplicate of #195 and #118 ? I think somewhere else was a comment that @RazrFalcon decided against it to prevent Input-files such as .PNG or .svgz .
But allowing some fileextensions such as .svg, .xml, .txt (because of Github), .tmp, .temp (because of #118), ...  might be a compromise?

**Comment by RazrFalcon** [comment]
Yes. The app is kinda dead. So do not expect much any time soon.

**Comment by desbma** [comment]
> @desbma Seems to be a duplicate of #195 and #118 

Yup, duplicate of #195.

> Yes. The app is kinda dead. So do not expect much any time soon.

Maybe it would be nice add a warning to the readme, so users can look at the alternatives instead?
