### ISSUE TITLE
Ubuntu 16.04 PPA fails to fetch

### ISSUE THREAD

**Issue by clessley** [RazrFalcon/SVGCleaner#29]
Won't install on Ubuntu 16.04 via PPA:

E: Failed to fetch http://ppa.launchpad.net/svg-cleaner-team/svgcleaner/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found

E: Unable to locate package svg-cleaner

**Comment by Grief** [comment]
That is not the issue since you can use `trusty` or `devel` dist. The real issue is that the package depends on `libqt4-core` and `libqt4-gui` which are not in ubuntu repositories anymore

**Comment by RazrFalcon** [comment]
There are no plans of updating ubuntu ppa, because project is freezed and I don't have time to write new build rules for newer Ubuntu's, which one I do no use.

You can build it from sources, if there is still Qt4 in repository, or make new ppa.

**Comment by Grief** [comment]
@clessley @RazrFalcon I've made some trivial changes to compile the project with QT5, not sure how stable it is, but some sanity checks successfully passed. I mean, I tried to minify a couple of adobe illustrated-generated SVGs and they were minified without an issue. However, please consider testing it instead of actually using it. I have never created ppa repositories, so I need some time to figure out how to do that.

**Comment by clessley** [comment]
@RazrFalcon that sounds promising! I wonder if reaching out to webupda8 would be worth while since they often will roll their own specific PPA's. A similar situation has occurred with youtube-dlg also due to Ubuntu's culling of dependencies.

**Comment by RazrFalcon** [comment]
@Grief. Yes, porting to Qt5 should be easy, because there is no hard Qt4 dependencies. And cleaning should work as planed.

But! But it will broke support of distros with Qt4 only, if there is any still. Also it will broke building on older ubuntu releases. So you should keep both version of code via ifdef. 

So this is already sound like a lot of work.

I'll accept yours patches, if you plan to make ppa from this repository. But project are steel freezed for unknown time.

I wrote new version from scratch, without Qt, but it's still very unstable and unfinished. And I don't have enough time to finish it. So no new version this year, probably.

**Comment by Grief** [comment]
@RazrFalcon Yes, I know how to wrap code with ifdef's, it's trivial and already done as I said. But I did the changes on the latest release tag, and I have one issue with the master branch: I don't get the reason of redefining `qHash` in `minidef`.

**Comment by Grief** [comment]
https://github.com/RazrFalcon/SVGCleaner/pull/30

**Comment by RazrFalcon** [comment]
Wait. You patched current branch? It's unfinished and outdated... I thought that you will patch v0.6.2 release. 

Here the deal: current muster branch has nothing to do with latest, 0.6.2, release. They didn't share any of code. Basically, current master - it's unfinished 0.7.0, but I drop it and start rewriting it from scratch.  But this version also unfinished and not available for public...

As you see, code base are complete mess, because I don't have enough time to fix it all.

If you really want to make ppa, you should create fork of 0.6.2 release with your patches.


About hashes, yes, it's some kind of optimization. But it must be defined, other vise it would not work. As far as I remember there are some problems with it in Qt5. Honestly, I didn't see svgcleaner code for more than year.

**Comment by Grief** [comment]
@RazrFalcon it's up to you, as I said, I've patched 0.6.2 as well. So I'll create another pull request later today. But I made some tests with the master branch and didn't find any major issues. The only thing I found was the message 'operation is in process, are you sure want to close?' when closing the GUI while the operation was actually finished. It could be related to the qt5 change though. Anyway, I'll make another pull request in the evening.

**Comment by RazrFalcon** [comment]
Main problem, is that I need to revert master branch to 0.6.2 state. Way back to Feb 16, 2014. I probably do it today.

**Comment by Grief** [comment]
@RazrFalcon I got your intention, what I didn't get is why do you think that it is broken when it's actually working. I mean there are some commits which are looking nice and good, like performance improvements and simplification of the code base, are you sure that you want to simply drop them? 

Anyway, this is your code and I am sure that you know what you do.

**Comment by RazrFalcon** [comment]
Well. Let I check it a bit. Test it for a couple of days. If everything is ok - it's probably better to just port master to Qt5, as you already did, and make 0.7 release. Why not.

**Comment by don-vip** [comment]
Is everything ok with these changes?

**Comment by clessley** [comment]
I've tried to install the Trusty ppa's and SVG continues to be impossible to install. I cannot install from @Grief fork either. Qtlib4-core at Debian's archive contains many files. I added the deb's from Trusty to the wiki but they are useless without the aforementioned dependencies. Is the final version of this for QT5 ever going to be released? Seems silly to run wine for this.

**Comment by RazrFalcon** [comment]
Not relevant anymore, since there will be a new package based on Rust.
