### ISSUE TITLE
Group by Transform

### ISSUE THREAD

**Issue by slyrz** [RazrFalcon/svgcleaner#71]
Hello Reizner, thanks for creating *svgcleaner*, it's a great project!

As the issue title suggests, have you considered grouping transforms the way you group styles?

```svg
<svg  xmlns="http://www.w3.org/2000/svg">
  <rect x="10" y="10" height="10" width="10" fill="#ff0000" transform="matrix(1 -1 0 1 0 0)"/>
  <rect x="20" y="20" height="10" width="10" fill="#ff0000" transform="matrix(1 -1 0 1 0 0)"/>
  <rect x="30" y="30" height="10" width="10" fill="#ff0000" transform="matrix(1 -1 0 1 0 0)"/>
</svg>
```

Currently svgcleaner (96611a3) produces the following output:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <g fill="#f00">
    <path d="m10 10h10v10h-10z" transform="matrix(1 -1 0 1 0 0)"/>
    <path d="m20 20h10v10h-10z" transform="matrix(1 -1 0 1 0 0)"/>
    <path d="m30 30h10v10h-10z" transform="matrix(1 -1 0 1 0 0)"/>
  </g>
</svg>
```

It could go even further and move the transform to the group-level as well:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <g fill="#f00" transform="matrix(1 -1 0 1 0 0)">
    <path d="m10 10h10v10h-10z"/>
    <path d="m20 20h10v10h-10z"/>
    <path d="m30 30h10v10h-10z"/>
  </g>
</svg>
```

This should be save to do for all types of transforms, no?

**Comment by RazrFalcon** [comment]
Hello. It's was planned in the old implementation, [kinda](https://github.com/RazrFalcon/svgcleaner/blob/f34df709fbc8546d3628e210bd97ee70407dba25/src/task/move_styles_to_group.rs#L88).

Yes, I can group equal transforms. I didn't implemented it yet, because I wanted to find a way to group transforms partially (for example extracting equal translate parts from transforms). But it probably would no work.

**Comment by RazrFalcon** [comment]
Done.

It works only for nodes that doesn't have any linked nodes, so no filter, clip-path etc.

**Comment by slyrz** [comment]
Thanks, works great!
